Installation of the new design
adrien-gueret/ShyComics pull request #86
Opened 2017-11-04 12:09 UTC by Tatane58

Let's install the new design !

2017-11-06 12:26 UTC, adrien-gueret requested changes

2017-11-06 12:26 UTC, adrien-gueret commented on application/views/index/header.php
> +                <?php endif; ?>-->
Ce fichier a beaucoup de code commenté, ça nuit à la lisibilité. Il faudrait simplement supprimer les lignes commentées : l'historique Git sert à les retrouver facilement ;)

2017-11-06 12:26 UTC, adrien-gueret commented on application/views/index/header.php
> +                Bandeau
Ce texte est en dur, il faudrait passer par une clé de traduction.

2017-11-06 12:26 UTC, adrien-gueret commented on application/views/index/index.php
> +    </div>
Ce fichier semble être un fichier-test/exemple, non ?
Il contient des textes non traduits, des `<div>` vides, des faux liens, des fausses données... 

C'est étrange, car il s'agit de l'index, ça me parait smelly, non ?

2017-11-06 12:26 UTC, adrien-gueret commented on public/images/LogoBlack.svg
> +
Essaye de passer les SVG dans des optimiseurs (genre SVGo) pour éviter d'avoir du contenu inutile dans ces fichiers (et donc avoir des SVG moins lourds et plus rapides à charger :) )

2017-11-06 12:26 UTC, adrien-gueret commented on application/views/index/index.php
> +                    <div></div><!--Necessary for puting the next div to the bottom-->
Pas sûr de comprendre ton problème de positionnement ici, ça devrait être possible de faire ça en CSS sans ajouter des `<div>` vides.

2017-11-12 14:22 UTC, Tatane58 commented on application/views/index/header.php
> +                Bandeau
Je l'ai laissé ainsi car pour l'instant il sert juste à voir si la mise en page marche. "Bandeau" sera remplacé par le titre de la page par la suite.

2017-11-12 14:22 UTC, Tatane58 commented on application/views/index/index.php
> +                    <div></div><!--Necessary for puting the next div to the bottom-->
Ben pourtant, sans ce div vide ça ne marchait pas.

2017-11-12 14:23 UTC, Tatane58 commented on application/views/index/index.php
> +    </div>
Pour l'instant je me suis occupé de mettre en place le design. Je ne me suis pas occupé de faire une page fonctionnelle du premier coup. Mais c'est ce que je fais actuellement.

2017-11-21 20:03 UTC, Tatane58 commented
As-tu vu mes modifications ?
J'attends des nouvelles de voxy ou toi pour continuer.

2017-11-21 20:05 UTC, adrien-gueret approved these changes

2017-11-21 20:05 UTC, adrien-gueret commented
Rha mais non, je n'ai pas été notifié par tes modifs, désolé >_>
Je merge :)

2017-11-21 20:05 UTC, merged